export type Difficulty = "Easy" | "Medium" | "Hard";
export type ProblemStatus = "solved" | "attempted" | "unsolved";
export type Category =
  | "All Topics"
  | "HTML & CSS"
  | "JavaScript DOM"
  | "React & UI"
  | "Web APIs"
  | "Node.js & Backend";

export interface Problem {
  id: number;
  title: string;
  slug: string;
  acceptance: string;
  difficulty: Difficulty;
  status: ProblemStatus;
  favorite: boolean;
  isFeatured?: boolean;
  isPremium?: boolean;
  hasSolution?: boolean;
  hasVideo?: boolean;
  category: Category;
  tags: string[];
  companies: string[];
  frequency?: number;
}

export interface TopicTag {
  name: string;
  count: number;
}

export interface Company {
  name: string;
  count: number;
  icon?: string;
}

export interface PromoBanner {
  id: string;
  title: string;
  subtitle: string;
  badge: string;
  cta: string;
  gradient: string;
  borderGlow: string;
  link: string;
}

export interface NavListItem {
  id: string;
  name: string;
  count: number;
  isPrivate: boolean;
}

export const MOCK_TOPICS: TopicTag[] = [
  { name: "CSS Grid & Flexbox", count: 480 },
  { name: "DOM Manipulation", count: 620 },
  { name: "React Hooks & State", count: 510 },
  { name: "Web APIs & Observers", count: 340 },
  { name: "Polyfills & Core JS", count: 310 },
  { name: "Accessibility (A11y)", count: 280 },
  { name: "Async & Promises", count: 390 },
  { name: "Performance & Virtualization", count: 210 },
  { name: "Drag & Drop", count: 140 },
  { name: "Form Validation", count: 250 },
  { name: "Auth & Security", count: 190 },
  { name: "Animations & Transitions", count: 160 },
  { name: "Event Delegation", count: 175 },
  { name: "State Machines", count: 120 },
  { name: "Design Systems", count: 230 },
  { name: "Component Architecture", count: 320 },
  { name: "Web Workers & Streams", count: 105 },
  { name: "Canvas & SVG", count: 90 },
];

export const MOCK_SAVED_TOPICS = [
  "CSS Grid & Flexbox",
  "DOM Manipulation",
  "React Hooks & State",
  "Polyfills & Core JS",
  "Accessibility (A11y)",
  "Performance & Virtualization",
];

export const MOCK_COMPANIES: Company[] = [
  { name: "Vercel", count: 420 },
  { name: "Stripe", count: 510 },
  { name: "Airbnb", count: 390 },
  { name: "Meta", count: 640 },
  { name: "Figma", count: 290 },
  { name: "Linear", count: 180 },
  { name: "Netflix", count: 340 },
  { name: "Uber", count: 410 },
  { name: "Shopify", count: 360 },
  { name: "Notion", count: 260 },
  { name: "Atlassian", count: 310 },
  { name: "Apple", count: 280 },
];

export const MOCK_PROMO_BANNERS: PromoBanner[] = [
  {
    id: "staqor-pro",
    title: "Staqor Pro 2026",
    subtitle: "Real-world Frontend & Web UI Challenges graded live with Groq AI in < 2.5s",
    badge: "$15 / mo",
    cta: "Upgrade Now",
    gradient: "from-[#0d231d] via-[#111c18] to-[#111117]",
    borderGlow: "border-primary/40 hover:border-primary",
    link: "/pricing",
  },
  {
    id: "frontend-system-design",
    title: "Frontend System Design 100",
    subtitle: "From Virtualized Feeds and Focus Traps to Collaborative Canvas Engines",
    badge: "Free Track",
    cta: "Start Quest",
    gradient: "from-[#1d1633] via-[#151324] to-[#111117]",
    borderGlow: "border-purple-500/30 hover:border-purple-400/60",
    link: "/problem?tag=Design+Systems",
  },
  {
    id: "weekly-ui-arena",
    title: "Weekly UI Arena #42",
    subtitle: "Build a Command Palette (Cmd+K) with Keyboard Navigation in 60 minutes",
    badge: "Starts in 2d",
    cta: "Register",
    gradient: "from-[#291a18] via-[#1c1415] to-[#111117]",
    borderGlow: "border-orange-500/30 hover:border-orange-400/60",
    link: "/contest",
  },
  {
    id: "30-days-web-apis",
    title: "30 Days of Modern Web APIs",
    subtitle: "IntersectionObserver, MutationObserver, Web Workers, Streams, & Storage",
    badge: "Active (Day 14)",
    cta: "Continue",
    gradient: "from-[#13222e] via-[#111921] to-[#111117]",
    borderGlow: "border-cyan-500/30 hover:border-cyan-400/60",
    link: "/problem?category=Web+APIs",
  },
];

export const MOCK_PROBLEMS: Problem[] = [
  // --- HTML & CSS ---
  {
    id: 1,
    title: "Responsive Bento Grid Layout with CSS Grid & Subgrid",
    slug: "responsive-bento-grid",
    acceptance: "68.4%",
    difficulty: "Easy",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "HTML & CSS",
    tags: ["CSS Grid & Flexbox", "Design Systems"],
    companies: ["Linear", "Vercel", "Apple"],
    frequency: 96,
  },
  {
    id: 2,
    title: "Glassmorphic Pricing Card with Monthly/Annual Billing Toggle",
    slug: "glassmorphic-pricing-table",
    acceptance: "74.1%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "HTML & CSS",
    tags: ["CSS Grid & Flexbox", "Animations & Transitions"],
    companies: ["Stripe", "Vercel", "Shopify"],
    frequency: 88,
  },
  {
    id: 3,
    title: "Accessible Dark & Light Theme System with CSS Custom Properties",
    slug: "accessible-dark-light-theme",
    acceptance: "81.2%",
    difficulty: "Easy",
    status: "solved",
    favorite: true,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "HTML & CSS",
    tags: ["Accessibility (A11y)", "Design Systems"],
    companies: ["GitHub", "Airbnb", "Meta"],
    frequency: 91,
  },
  {
    id: 4,
    title: "Skeleton Loading Shimmer with Zero-JS CSS Keyframes",
    slug: "skeleton-loading-shimmer",
    acceptance: "79.5%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "HTML & CSS",
    tags: ["Animations & Transitions", "Performance & Virtualization"],
    companies: ["Facebook", "Netflix", "Uber"],
    frequency: 84,
  },
  {
    id: 5,
    title: "Sticky Header with Dynamic Reading Progress Bar",
    slug: "sticky-header-progress-bar",
    acceptance: "62.0%",
    difficulty: "Medium",
    status: "attempted",
    favorite: false,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "HTML & CSS",
    tags: ["CSS Grid & Flexbox", "DOM Manipulation"],
    companies: ["Medium", "Notion", "Substack"],
    frequency: 78,
  },
  {
    id: 6,
    title: "Infinite Smooth Marquee Carousel using CSS Transforms",
    slug: "infinite-css-marquee",
    acceptance: "58.7%",
    difficulty: "Medium",
    status: "unsolved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "HTML & CSS",
    tags: ["Animations & Transitions", "CSS Grid & Flexbox"],
    companies: ["Shopify", "Vercel", "Stripe"],
    frequency: 72,
  },

  // --- JavaScript DOM & Core Polyfills ---
  {
    id: 7,
    title: "Implement Custom Promise.all & Promise.allSettled Polyfill",
    slug: "promise-all-allsettled-polyfill",
    acceptance: "44.3%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "JavaScript DOM",
    tags: ["Polyfills & Core JS", "Async & Promises"],
    companies: ["Meta", "Google", "Uber", "Amazon"],
    frequency: 98,
  },
  {
    id: 8,
    title: "Debounce Function with Immediate Execution & Cancel Method",
    slug: "debounce-immediate-cancel",
    acceptance: "52.8%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "JavaScript DOM",
    tags: ["Polyfills & Core JS", "DOM Manipulation"],
    companies: ["Stripe", "Meta", "TikTok", "Airbnb"],
    frequency: 97,
  },
  {
    id: 9,
    title: "Throttle Function with Leading & Trailing Edge Options",
    slug: "throttle-leading-trailing",
    acceptance: "39.1%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "JavaScript DOM",
    tags: ["Polyfills & Core JS", "DOM Manipulation"],
    companies: ["Google", "Uber", "Netflix", "Atlassian"],
    frequency: 95,
  },
  {
    id: 10,
    title: "Deep Clone with Circular References & Symbol Key Handling",
    slug: "deep-clone-circular-references",
    acceptance: "36.4%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "JavaScript DOM",
    tags: ["Polyfills & Core JS"],
    companies: ["Meta", "ByteDance", "Amazon"],
    frequency: 89,
  },
  {
    id: 11,
    title: "Typeahead Search with Keyboard Navigation & Match Highlighting",
    slug: "typeahead-autocomplete-component",
    acceptance: "48.6%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "JavaScript DOM",
    tags: ["DOM Manipulation", "Accessibility (A11y)", "Event Delegation"],
    companies: ["Google", "Amazon", "Stripe", "Airbnb"],
    frequency: 94,
  },
  {
    id: 12,
    title: "Native Drag-and-Drop Kanban Board with Column Reordering",
    slug: "kanban-native-drag-drop",
    acceptance: "41.9%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "JavaScript DOM",
    tags: ["Drag & Drop", "DOM Manipulation", "Design Systems"],
    companies: ["Atlassian", "Trello", "Notion", "Linear"],
    frequency: 92,
  },
  {
    id: 13,
    title: "Custom EventEmitter & Pub-Sub Event Bus with Once Handler",
    slug: "custom-event-emitter-pubsub",
    acceptance: "61.2%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "JavaScript DOM",
    tags: ["Polyfills & Core JS", "Component Architecture"],
    companies: ["Netflix", "Spotify", "Shopify"],
    frequency: 86,
  },
  {
    id: 14,
    title: "Event Delegation Table with Dynamic Multi-Row Selection",
    slug: "event-delegation-table-selection",
    acceptance: "55.0%",
    difficulty: "Medium",
    status: "attempted",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "JavaScript DOM",
    tags: ["Event Delegation", "DOM Manipulation"],
    companies: ["Airtable", "Notion", "Google"],
    frequency: 81,
  },
  {
    id: 15,
    title: "Resizable Split Pane Component with Boundary Constraints",
    slug: "resizable-split-pane",
    acceptance: "46.3%",
    difficulty: "Medium",
    status: "unsolved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "JavaScript DOM",
    tags: ["DOM Manipulation", "Component Architecture"],
    companies: ["VS Code / Microsoft", "Figma", "Replit"],
    frequency: 83,
  },

  // --- React & UI Component Systems ---
  {
    id: 16,
    title: "Custom useQuery Hook with Memory Cache, Deduping & Stale Time",
    slug: "use-query-cache-deduping",
    acceptance: "38.7%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "React & UI",
    tags: ["React Hooks & State", "Async & Promises"],
    companies: ["Vercel", "Meta", "TanStack"],
    frequency: 96,
  },
  {
    id: 17,
    title: "WAI-ARIA Compliant Compound Modal with Focus Trap & Escape Key",
    slug: "accessible-focus-trap-modal",
    acceptance: "47.2%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "React & UI",
    tags: ["Accessibility (A11y)", "React Hooks & State", "Design Systems"],
    companies: ["Airbnb", "Apple", "Stripe", "Radix UI"],
    frequency: 93,
  },
  {
    id: 18,
    title: "Multi-Step Checkout Wizard with LocalStorage State Persistence",
    slug: "multi-step-checkout-wizard",
    acceptance: "64.5%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "React & UI",
    tags: ["React Hooks & State", "Form Validation"],
    companies: ["Shopify", "Stripe", "Amazon"],
    frequency: 87,
  },
  {
    id: 19,
    title: "Custom useVirtualizer Hook for Rendering 50,000 List Items at 60fps",
    slug: "custom-virtualized-list",
    acceptance: "31.4%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "React & UI",
    tags: ["Performance & Virtualization", "React Hooks & State"],
    companies: ["Meta", "Twitter/X", "Linear", "Discord"],
    frequency: 97,
  },
  {
    id: 20,
    title: "Compound Accordion Component with Animated Content Expansion",
    slug: "compound-accordion-animation",
    acceptance: "69.1%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "React & UI",
    tags: ["Component Architecture", "Accessibility (A11y)"],
    companies: ["Vercel", "Tailwind Labs", "Figma"],
    frequency: 82,
  },
  {
    id: 21,
    title: "Optimistic UI Mutation with Auto-Rollback on Server Error",
    slug: "optimistic-ui-mutation-rollback",
    acceptance: "45.8%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "React & UI",
    tags: ["React Hooks & State", "Async & Promises"],
    companies: ["Linear", "Superhuman", "Notion"],
    frequency: 91,
  },
  {
    id: 22,
    title: "Interactive Command Palette (Cmd+K) with Fuzzy Filter & Actions",
    slug: "cmd-k-command-palette",
    acceptance: "42.5%",
    difficulty: "Hard",
    status: "attempted",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "React & UI",
    tags: ["Accessibility (A11y)", "Design Systems", "DOM Manipulation"],
    companies: ["Vercel", "Raycast", "Linear", "GitHub"],
    frequency: 95,
  },

  // --- Web APIs & Browser Performance ---
  {
    id: 23,
    title: "Infinite Image Feed with IntersectionObserver & Lazy Loading",
    slug: "intersection-observer-infinite-feed",
    acceptance: "59.3%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "Web APIs",
    tags: ["Web APIs & Observers", "Performance & Virtualization"],
    companies: ["Pinterest", "Instagram", "Unsplash"],
    frequency: 90,
  },
  {
    id: 24,
    title: "In-Browser Web Worker for Heavy CSV Parsing & Data Aggregation",
    slug: "web-worker-csv-parser",
    acceptance: "49.0%",
    difficulty: "Medium",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "Web APIs",
    tags: ["Web Workers & Streams", "Performance & Virtualization"],
    companies: ["Figma", "Tableau", "Datadog"],
    frequency: 85,
  },
  {
    id: 25,
    title: "Browser Storage Cache Manager with LRU Eviction & TTL Expiration",
    slug: "browser-storage-lru-ttl",
    acceptance: "43.7%",
    difficulty: "Medium",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Web APIs",
    tags: ["Web APIs & Observers", "Polyfills & Core JS"],
    companies: ["Netflix", "Spotify", "Amazon"],
    frequency: 88,
  },
  {
    id: 26,
    title: "Real-time Live Audio Waveform Visualizer using Web Audio API",
    slug: "web-audio-waveform-visualizer",
    acceptance: "33.2%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Web APIs",
    tags: ["Canvas & SVG", "Web APIs & Observers"],
    companies: ["Spotify", "Discord", "Apple"],
    frequency: 79,
  },

  // --- Node.js & Backend / Full-Stack ---
  {
    id: 27,
    title: "Token Bucket Rate Limiting Middleware with Redis / In-Memory Map",
    slug: "token-bucket-rate-limiter",
    acceptance: "48.1%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Node.js & Backend",
    tags: ["Auth & Security", "Async & Promises"],
    companies: ["Cloudflare", "Stripe", "GitHub", "AWS"],
    frequency: 94,
  },
  {
    id: 28,
    title: "JWT Authentication Handler with Refresh Token Rotation & Cookie Sync",
    slug: "jwt-refresh-token-rotation",
    acceptance: "40.5%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Node.js & Backend",
    tags: ["Auth & Security"],
    companies: ["Auth0", "Stripe", "Vercel", "Uber"],
    frequency: 92,
  },
  {
    id: 29,
    title: "Server-Sent Events (SSE) Live Feed Handler with Client Reconnect",
    slug: "server-sent-events-live-feed",
    acceptance: "51.4%",
    difficulty: "Medium",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Node.js & Backend",
    tags: ["Web Workers & Streams", "Async & Promises"],
    companies: ["OpenAI", "Twitter/X", "Datadog"],
    frequency: 89,
  },
  {
    id: 30,
    title: "Multipart File Upload Streamer with Chunk Verification & Hash Check",
    slug: "chunked-file-upload-stream",
    acceptance: "35.8%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Node.js & Backend",
    tags: ["Web Workers & Streams", "Auth & Security"],
    companies: ["Dropbox", "Box", "Google Drive", "AWS"],
    frequency: 93,
  },
];
