export type Difficulty = "Easy" | "Medium" | "Hard";
export type ProblemStatus = "solved" | "attempted" | "unsolved";
export type Category = "All Topics" | "Algorithms" | "Database" | "Shell" | "Concurrency" | "JavaScript";

export interface Problem {
  id: number;
  title: string;
  slug: string;
  acceptance: string;
  difficulty: Difficulty;
  status: ProblemStatus;
  favorite: boolean;
  isFeatured?: boolean;
  isPremium?: boolean;
  hasSolution?: boolean;
  hasVideo?: boolean;
  category: Category;
  tags: string[];
  companies: string[];
  frequency?: number;
}

export interface TopicTag {
  name: string;
  count: number;
}

export interface Company {
  name: string;
  count: number;
  icon?: string;
}

export interface PromoBanner {
  id: string;
  title: string;
  subtitle: string;
  badge: string;
  cta: string;
  gradient: string;
  borderGlow: string;
  link: string;
}

export interface NavListItem {
  id: string;
  name: string;
  count: number;
  isPrivate: boolean;
}

export const MOCK_TOPICS: TopicTag[] = [
  { name: "Array", count: 2238 },
  { name: "String", count: 893 },
  { name: "Hash Table", count: 832 },
  { name: "Dynamic Programming", count: 678 },
  { name: "Math", count: 702 },
  { name: "Sorting", count: 534 },
  { name: "Greedy", count: 481 },
  { name: "Depth-First Search", count: 412 },
  { name: "Binary Search", count: 320 },
  { name: "Tree", count: 420 },
  { name: "Breadth-First Search", count: 310 },
  { name: "Two Pointers", count: 265 },
  { name: "Matrix", count: 280 },
  { name: "Stack", count: 240 },
  { name: "Graph", count: 215 },
  { name: "Linked List", count: 190 },
  { name: "Recursion", count: 175 },
  { name: "Prefix Sum", count: 160 },
  { name: "JavaScript DOM", count: 145 },
  { name: "Bit Manipulation", count: 130 },
  { name: "Backtracking", count: 120 },
  { name: "Sliding Window", count: 110 },
  { name: "Design / System", count: 95 },
  { name: "Trie", count: 65 },
];

export const MOCK_SAVED_TOPICS = [
  "Binary Search",
  "Recursion",
  "Prefix Sum",
  "Linked List",
  "Stack",
  "Dynamic Programming",
];

export const MOCK_COMPANIES: Company[] = [
  { name: "Google", count: 2350 },
  { name: "Amazon", count: 2021 },
  { name: "Meta", count: 1840 },
  { name: "Microsoft", count: 1620 },
  { name: "Apple", count: 295 },
  { name: "TikTok", count: 342 },
  { name: "Uber", count: 890 },
  { name: "Netflix", count: 410 },
  { name: "Bloomberg", count: 750 },
  { name: "Stripe", count: 310 },
  { name: "Adobe", count: 520 },
  { name: "Oracle", count: 430 },
];

export const MOCK_PROMO_BANNERS: PromoBanner[] = [
  {
    id: "staqor-pro",
    title: "Staqor Pro 2026",
    subtitle: "Master Real Frontend & UI Challenges with Sub-2.5s Groq AI Evaluation",
    badge: "$15 / mo",
    cta: "Upgrade Now",
    gradient: "from-[#0d231d] via-[#111c18] to-[#111117]",
    borderGlow: "border-primary/40 hover:border-primary",
    link: "/pricing",
  },
  {
    id: "top-interview-150",
    title: "Top 150 Interview Classics",
    subtitle: "The most tested algorithms & data structures for FAANG + Tier-1 startups",
    badge: "Free Track",
    cta: "Start Quest",
    gradient: "from-[#1d1633] via-[#151324] to-[#111117]",
    borderGlow: "border-purple-500/30 hover:border-purple-400/60",
    link: "/problem?tag=Top150",
  },
  {
    id: "weekly-contest",
    title: "Weekly Arena #438",
    subtitle: "Compete live this Saturday at 8:00 PM EST. 4 problems, instant rating updates.",
    badge: "Starts in 2d",
    cta: "Register",
    gradient: "from-[#291a18] via-[#1c1415] to-[#111117]",
    borderGlow: "border-orange-500/30 hover:border-orange-400/60",
    link: "/contest",
  },
  {
    id: "30-days-js",
    title: "30 Days of JS & DOM",
    subtitle: "Closures, Event Loop, Polyfills, Virtual DOM, and Custom React Replicas",
    badge: "Active (Day 14)",
    cta: "Continue",
    gradient: "from-[#13222e] via-[#111921] to-[#111117]",
    borderGlow: "border-cyan-500/30 hover:border-cyan-400/60",
    link: "/problem?category=JavaScript",
  },
];

export const MOCK_PROBLEMS: Problem[] = [
  {
    id: 1,
    title: "Two Sum",
    slug: "two-sum",
    acceptance: "54.2%",
    difficulty: "Easy",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Array", "Hash Table"],
    companies: ["Google", "Amazon", "Meta", "Apple"],
    frequency: 98,
  },
  {
    id: 2,
    title: "Add Two Numbers",
    slug: "add-two-numbers",
    acceptance: "43.1%",
    difficulty: "Medium",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Linked List", "Math", "Recursion"],
    companies: ["Amazon", "Microsoft", "Bloomberg"],
    frequency: 88,
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    slug: "longest-substring-without-repeating-characters",
    acceptance: "35.8%",
    difficulty: "Medium",
    status: "attempted",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Hash Table", "String", "Sliding Window"],
    companies: ["Meta", "Google", "Amazon", "TikTok"],
    frequency: 92,
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    slug: "median-of-two-sorted-arrays",
    acceptance: "41.2%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: false,
    isFeatured: true,
    hasSolution: true,
    hasVideo: false,
    category: "Algorithms",
    tags: ["Array", "Binary Search", "Divide and Conquer"],
    companies: ["Google", "Amazon", "Microsoft"],
    frequency: 85,
  },
  {
    id: 5,
    title: "Longest Palindromic Substring",
    slug: "longest-palindromic-substring",
    acceptance: "34.6%",
    difficulty: "Medium",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Two Pointers", "String", "Dynamic Programming"],
    companies: ["Amazon", "Microsoft", "Apple"],
    frequency: 79,
  },
  {
    id: 6,
    title: "Zigzag Conversion",
    slug: "zigzag-conversion",
    acceptance: "48.9%",
    difficulty: "Medium",
    status: "unsolved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Algorithms",
    tags: ["String"],
    companies: ["Paypal", "Amazon"],
    frequency: 45,
  },
  {
    id: 7,
    title: "Reverse Integer",
    slug: "reverse-integer",
    acceptance: "29.4%",
    difficulty: "Medium",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Algorithms",
    tags: ["Math"],
    companies: ["Apple", "Bloomberg"],
    frequency: 60,
  },
  {
    id: 8,
    title: "String to Integer (atoi)",
    slug: "string-to-integer-atoi",
    acceptance: "18.2%",
    difficulty: "Medium",
    status: "unsolved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["String"],
    companies: ["Meta", "Microsoft"],
    frequency: 58,
  },
  {
    id: 9,
    title: "Palindrome Number",
    slug: "palindrome-number",
    acceptance: "57.8%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Math"],
    companies: ["Amazon", "Google"],
    frequency: 74,
  },
  {
    id: 10,
    title: "Regular Expression Matching",
    slug: "regular-expression-matching",
    acceptance: "29.1%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: false,
    category: "Algorithms",
    tags: ["String", "Dynamic Programming", "Recursion"],
    companies: ["Google", "Meta", "Uber"],
    frequency: 81,
  },
  {
    id: 11,
    title: "Container With Most Water",
    slug: "container-with-most-water",
    acceptance: "56.4%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Array", "Two Pointers", "Greedy"],
    companies: ["Amazon", "Meta", "Google"],
    frequency: 90,
  },
  {
    id: 12,
    title: "Integer to Roman",
    slug: "integer-to-roman",
    acceptance: "65.2%",
    difficulty: "Medium",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Algorithms",
    tags: ["Hash Table", "Math", "String"],
    companies: ["Twitter", "Amazon"],
    frequency: 52,
  },
  {
    id: 13,
    title: "Roman to Integer",
    slug: "roman-to-integer",
    acceptance: "62.1%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Hash Table", "Math", "String"],
    companies: ["Amazon", "Apple", "Google"],
    frequency: 84,
  },
  {
    id: 14,
    title: "Longest Common Prefix",
    slug: "longest-common-prefix",
    acceptance: "44.3%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Algorithms",
    tags: ["String", "Trie"],
    companies: ["Amazon", "Google", "Adobe"],
    frequency: 72,
  },
  {
    id: 15,
    title: "3Sum",
    slug: "3sum",
    acceptance: "35.7%",
    difficulty: "Medium",
    status: "attempted",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Array", "Two Pointers", "Sorting"],
    companies: ["Meta", "Amazon", "Google", "Apple", "Microsoft"],
    frequency: 96,
  },
  {
    id: 16,
    title: "Implement Debounce & Throttle Polyfill",
    slug: "debounce-throttle-polyfill",
    acceptance: "48.2%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "JavaScript",
    tags: ["JavaScript DOM", "Closures", "Async"],
    companies: ["Stripe", "Uber", "Meta", "TikTok"],
    frequency: 94,
  },
  {
    id: 17,
    title: "Deep Clone with Circular Reference Support",
    slug: "deep-clone-circular",
    acceptance: "39.5%",
    difficulty: "Medium",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "JavaScript",
    tags: ["JavaScript DOM", "Recursion", "Hash Table"],
    companies: ["Google", "Meta", "ByteDance"],
    frequency: 82,
  },
  {
    id: 18,
    title: "Interactive Kanban Board with HTML5 Drag & Drop",
    slug: "kanban-drag-and-drop",
    acceptance: "42.0%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "JavaScript",
    tags: ["JavaScript DOM", "Design / System"],
    companies: ["Atlassian", "Stripe", "Notion"],
    frequency: 87,
  },
  {
    id: 19,
    title: "Accessible Tabs Component with ARIA & Keyboard Nav",
    slug: "accessible-tabs-component",
    acceptance: "31.4%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: false,
    category: "JavaScript",
    tags: ["JavaScript DOM", "Design / System"],
    companies: ["Airbnb", "Apple", "Microsoft"],
    frequency: 76,
  },
  {
    id: 20,
    title: "Valid Parentheses",
    slug: "valid-parentheses",
    acceptance: "41.5%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["String", "Stack"],
    companies: ["Amazon", "Meta", "Bloomberg"],
    frequency: 93,
  },
  {
    id: 21,
    title: "Merge Two Sorted Lists",
    slug: "merge-two-sorted-lists",
    acceptance: "65.4%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Linked List", "Recursion"],
    companies: ["Amazon", "Microsoft", "Apple"],
    frequency: 89,
  },
  {
    id: 22,
    title: "Generate Parentheses",
    slug: "generate-parentheses",
    acceptance: "75.9%",
    difficulty: "Medium",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Algorithms",
    tags: ["String", "Dynamic Programming", "Backtracking"],
    companies: ["Meta", "Google", "Amazon"],
    frequency: 83,
  },
  {
    id: 23,
    title: "Merge k Sorted Lists",
    slug: "merge-k-sorted-lists",
    acceptance: "53.8%",
    difficulty: "Hard",
    status: "unsolved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Linked List", "Divide and Conquer", "Sorting"],
    companies: ["Meta", "Amazon", "Google", "ByteDance"],
    frequency: 91,
  },
  {
    id: 24,
    title: "Employees Earning More Than Their Managers",
    slug: "employees-earning-more-than-managers",
    acceptance: "71.2%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Database",
    tags: ["Database", "SQL"],
    companies: ["Amazon", "Bloomberg"],
    frequency: 68,
  },
  {
    id: 25,
    title: "Duplicate Emails",
    slug: "duplicate-emails",
    acceptance: "73.4%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Database",
    tags: ["Database", "SQL"],
    companies: ["Google", "Amazon"],
    frequency: 61,
  },
  {
    id: 26,
    title: "Tenth Line (Print 10th line of file)",
    slug: "tenth-line",
    acceptance: "35.1%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Shell",
    tags: ["Shell", "Bash"],
    companies: ["Amazon", "Oracle"],
    frequency: 42,
  },
  {
    id: 27,
    title: "Print in Order (Thread Concurrency)",
    slug: "print-in-order",
    acceptance: "69.8%",
    difficulty: "Easy",
    status: "solved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Concurrency",
    tags: ["Concurrency", "Multithreading"],
    companies: ["Google", "Microsoft"],
    frequency: 55,
  },
  {
    id: 28,
    title: "Building H2O Molecules (Barrier Sync)",
    slug: "building-h2o",
    acceptance: "59.2%",
    difficulty: "Medium",
    status: "unsolved",
    favorite: false,
    isFeatured: false,
    hasSolution: true,
    hasVideo: false,
    category: "Concurrency",
    tags: ["Concurrency", "Multithreading"],
    companies: ["Google", "Uber"],
    frequency: 48,
  },
  {
    id: 29,
    title: "LRU Cache Implementation",
    slug: "lru-cache",
    acceptance: "44.0%",
    difficulty: "Medium",
    status: "solved",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Hash Table", "Linked List", "Design / System"],
    companies: ["Amazon", "Google", "Meta", "Microsoft", "Apple"],
    frequency: 97,
  },
  {
    id: 30,
    title: "Trapping Rain Water",
    slug: "trapping-rain-water",
    acceptance: "62.4%",
    difficulty: "Hard",
    status: "attempted",
    favorite: true,
    isFeatured: true,
    hasSolution: true,
    hasVideo: true,
    category: "Algorithms",
    tags: ["Array", "Two Pointers", "Dynamic Programming", "Stack"],
    companies: ["Google", "Amazon", "Meta", "Goldman Sachs"],
    frequency: 99,
  },
];
